version: "3.8"

services:
    nest1:
        build:
            context: .
            dockerfile: ./dockerfile
        env_file: .env
        image: ghcr.io/klaus9267/summer-auto-deploy
        ports:
            - 3000:3000
        container_name: nest-prod1
        restart: always
    nest2:
        build:
            context: .
            dockerfile: ./dockerfile
        env_file: .env
        image: ghcr.io/klaus9267/summer-auto-deploy
        ports:
            - 4000:4000
        container_name: nest-prod2
        restart: always
    nest3:
        build:
            context: .
            dockerfile: ./dockerfile
        env_file: .env
        image: ghcr.io/klaus9267/summer-auto-deploy
        ports:
            - 5000:5000
        container_name: nest-prod3
        restart: always
